python/web/learn_site/info/urls.py
from django.urls import path
from .views.pages import info_index, handle_page_create, handle_page_get
from .views.tags import add_new_tag, show_tag_details, tag_glossary, edit_tag_view
from .views.comments import create_comment_view, comments_views

urlpatterns = [
    path("", info_index, name="users"),
    path("page/<uuid:id>/<str:title>", handle_page_get, name="get_page"),
    path("page/add", handle_page_create, name="post_page"),
    path("tags/add", add_new_tag, name="adding tags"),
    path("tag/<uuid:id>/<str:name>", show_tag_details, name="tag glossary"),
    path("tags/glossary", tag_glossary, name="tag glossary"),
    path("tags/edit/<uuid:id>/<str:name>", edit_tag_view, name="edit tag"),
    path("comments/add", create_comment_view, name="comment add"),
    path("comments/all", comments_views, name="all comments")
]

python/web/learn_site/learn_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("", include("info.urls")),
    path("", include("quizzes.urls"))
]

python/web/learn_site/info/models.py
from django.db import models
import uuid
from django.utils import timezone

# Create your models here.
class Tags(models.Model):

    class Meta:
        db_table = 'info_tags'
        managed = True

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    pages = models.ManyToManyField("Pages", blank=True, related_name="Tags")
    details = models.TextField(null=True, blank=True, default="")
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = ("Tags")

    def add_tag(self, name, details="", pages_optional="", *args, **kwargs):
        new = Tags(name=name, details=details)
        new.save()

        if pages_optional != "":
            new.pages.add(pages_optional)

    def add_pages(self, pages: list):
        for page in pages:
            self.Tags.add(page)
        
        return self.Pages

    def delete_pages(self, pages: list):
        for page in pages:
            self.Pages.remove(page)

    def update_name(self, name):
        self.name = name
        self.save()

        return self.name

    def delete_tag(self):
        try:
            pages = self.pages

            for page in pages:
                page.tags.remove(self)

            self.delete()

            return 1
        
        except:
            return -1

    @staticmethod
    def check_if_valid(name):
        results = Tags.objects.filter(name=name).exists()
        return results
        
    @staticmethod    
    def list_all():
        results = Tags.objects.all().values_list("name", flat=True)
        return results
    
    @staticmethod
    def set_all():
        results = Tags.objects.all()
        end = []
        for res in results:
            res.refresh_from_db()
            ou = (res.id, res.name)
            end.append(ou)

        return end
    
    def show_pages(self):
        return self.pages.all()
    
    def __str__(self):
        return f"{self.name}"


class Pages(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    data = models.TextField()
    tags = models.ManyToManyField("Tags", blank=True, related_name="Pages")

    class Meta:
        verbose_name_plural = ("Pages")

    def __str__(self):
        return f"{self.title} | {self.id}"
    
    def add_page(self, title, data):
        new_page = Pages(title=title, data=data)
        new_page.save()

        return new_page.id
    
    def show_tags(self):
        return self.Tags.all()
    
    def add_tag(self, tag_id):

        try:
            tag = Tags.objects.get(id=tag_id)
            self.tags.add(tag)
            self.save()
            return 1
        
        except:
            return -1


    def delete_tag(self, tag_id):
        try:
            tag = Tags.objects.get(id=tag_id)
            self.tags.remove(tag)
            self.save()

            return 1
        except:
            return -1
    
    def add_comment(self, text, user):
        comment = Comment(text=text, user=user.id, page=self.id)
    
class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    pages = models.ForeignKey("Pages", blank=True, null=True ,on_delete=models.SET_NULL)
    user = models.ForeignKey("users.User", on_delete=models.SET_NULL, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return f"{self.id} | {self.text}"

    @staticmethod
    def add_comment( text: str, user, page: Pages):
        new_comment = Comment(text=text, user=user, pages=page)
        new_comment.save()

        return new_comment


    

python/web/learn_site/info/forms.py
from django import forms
from .models import Tags

class create_new_page(forms.Form):

    def __init__(self, *args, **kwargs):
        super(create_new_page, self).__init__(*args, **kwargs)
        self.fields['tags'].choices = Tags.set_all()

    title = forms.CharField(max_length=255, help_text="please enter the title of this page")
    data = forms.CharField(widget=forms.Textarea)
    OPTIONS = Tags.set_all()
    tags = forms.MultipleChoiceField(help_text="Please enter the name for this tag", widget=forms.CheckboxSelectMultiple,
    choices=OPTIONS, required=False)

class add_tags_to_page(forms.Form):
    page = forms.UUIDField()
    OPTIONS = Tags.set_all()
    tags = forms.MultipleChoiceField(help_text="Please enter the name for this tag", widget=forms.CheckboxSelectMultiple,
    choices=OPTIONS)

class create_new_tag(forms.Form):
    name = forms.CharField(max_length=255, help_text="please enter name of tag")
    details = forms.CharField(widget=forms.Textarea, required=False)
    
class edit_tag(forms.Form):
    name = forms.CharField(max_length=255, help_text="please enter name of tag")
    details = forms.CharField(widget=forms.Textarea, required=False)

class create_comment(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    page_id = forms.UUIDField()
    user_id = forms.UUIDField()

python/web/learn_site/info/views/comments.py
from ..models import Comment, Pages
from users.models import User
from ..forms import create_comment
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


@login_required
@require_POST
def create_comment_view(request):
    user = request.user

    form = create_comment(request.POST)

    if form.is_valid():

        # params = request.POST.dict()
        # print(params)
        # try:
        #     user_id = params["user_id"]
        #     page_id = params["page_id"]
        # except KeyError:
        #     html_content = "<a href='/'><button>home</button></a><p>no user id or page id</p>"
        #     return HttpResponse(html_content, content_type="text/html")
        
        user_id = form.cleaned_data["user_id"]
        page_id = form.cleaned_data["page_id"]

        user = get_object_or_404(User, id=user_id)
        page = get_object_or_404(Pages, id=page_id)

        text = form.cleaned_data["text"]
        Comment.add_comment(text=text, user=user, page=page)

        return HttpResponseRedirect(f"/page/{page_id}/comment_add")
    
def comments_views(request):
    return HttpResponse("responding")
    

python/web/learn_site/info/views/pages.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from ..models import Pages, Tags
from ..forms import create_new_page, create_new_tag, create_comment
from django.utils.text import slugify
from users.models import Bookmark

def info_index(request):
    pages = Pages.objects.all().values()
    tags = Tags.objects.all()
    template = loader.get_template('index.html')

    context = {
        "pages" : pages,
        "tags": tags
    }

    # print(request.GET.dict())

    return HttpResponse(template.render(context, request))

def handle_page_get(request, id, title):
    page_get = get_object_or_404(Pages, id=id)

    tags = page_get.Tags.all()

    comment_form = create_comment(initial={"user_id":request.user.id, "page_id":page_get.id})

    comments = page_get.comment_set.all()

    bookmarked = False
    if request.user.is_authenticated:
        bookmarks = request.user.bookmark_set.all()
        for bookmark in bookmarks:
            if bookmark.page_id == page_get.id:
                bookmarked = True
    

    template = loader.get_template("default_Page.html")

    context = {
        "page" : page_get, 
        "tags" : tags,
        "comment_form": comment_form,
        "comments": comments,
        "bookmarked": bookmarked
    }

    return HttpResponse(template.render(context, request))

def handle_page_create(request):

    if request.method == "POST":
        form = create_new_page(request.POST)

        if form.is_valid():
            data = form.cleaned_data
    
            tags = form.cleaned_data["tags"]

            title = data["title"]
            title_slug = slugify(title, allow_unicode=True)

            new_page = Pages(title=title_slug, data=data["data"])

            new_page.save()

            for tag in tags:
                real_t = Tags.objects.get(id=tag)
                new_page.Tags.add(real_t)
            
            id = new_page.id
            title = new_page.title

            return HttpResponseRedirect(f"/page/{id}/{title}")
    
    else:
        form = create_new_page()

        #print(form)

        form_tag = create_new_tag()

        #print(form)
        #print(Tags.set_all())

        template = loader.get_template("add_page.html")

        context = {
            "form_tag" : form_tag,
            "form" : form
        }

        return HttpResponse(template.render(context, request))
    

python/web/learn_site/info/views/tags.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from ..models import  Tags
from ..forms import  create_new_tag, edit_tag
from django.utils.text import slugify

def add_new_tag(request):
    if request.method == "POST":
        form = create_new_tag(request.POST)

        if form.is_valid():
            name = slugify(form.cleaned_data["name"], allow_unicode=True).capitalize()
            details = form.cleaned_data["details"]

            if Tags.check_if_valid(name=name):
                return HttpResponse("Error: tag already exists")
            
            if details != "":
                new_tag = Tags(name=name, details=details)
                new_tag.save()
            else:
                new_tag = Tags(name=name)
                new_tag.save()

            return HttpResponseRedirect("/page/add")
    else:
        return HttpResponse("na")

def show_tag_details(request, name, id):
    tag = get_object_or_404(Tags, id=id)

    pages = tag.pages.all()

    template = loader.get_template("tag_page.html")

    context = {
        "tag" : tag,
        "pages" : pages
    }

    return HttpResponse(template.render(context, request))

def edit_tag_view(request, name, id):
    tag = get_object_or_404(Tags, id=id)

    if request.method == "POST":
        form = edit_tag(request.POST)

        if form.is_valid():
            print(slugify(form.cleaned_data["name"]))
            name = slugify(form.cleaned_data["name"], allow_unicode=True)
            details = form.cleaned_data["details"]
            
            if details != "":
                tag.details = details
                tag.name = name
                tag.save()
            else:
                tag.name = name
                tag.save()
            
            return HttpResponseRedirect(f"/tag/{tag.id}/{tag.name}")
    
    else:
        form = edit_tag(initial={"name":tag.name, "details":tag.details})

        template = loader.get_template("edit_tag.html")

        context = {
            "form_tag" : form,
        }

        return HttpResponse(template.render(context, request))
        

def tag_glossary(request):
    tags = Tags.objects.all()

    template = loader.get_template("tag_glossary.html")

    context = {
        "tags" : tags
    }

    return HttpResponse(template.render(context, request))

python/web/learn_site/info/templates/add_page.html
<html>
    <style>
        #id_data {
            width: 100vw;
        }
    </style>
    <body>
        <h1>Add a page!</h1>

        <form action="/tags/add" method="POST">
            {% csrf_token %}
            <ul>{{form_tag.as_ul}}</ul>
            <input type="submit" value="submit">
        </form>
        
        <form action="" method="POST">
            {% csrf_token %}
            <ul>
                {{form.as_ul}}
            </ul>
            <input type="submit" value="Submit">
        </form>
    </body>

python/web/learn_site/info/templates/default_page.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            .editable-content {
                width: 100%;
                height: 100%;
                box-sizing: border-box; /* Include padding and border in the element's total width and height */
                padding: 10px; /* Add padding as needed */
                outline: none; /* Remove the default outline when the div is focused */
            }

            .editable-div {
                width: 90vw; /* Set your desired width */
                border: 1px solid #ccc;
                overflow: auto; /* Hide content that overflows the div */
            }

            .limited-height-div {
                max-height: 20vh;
                overflow-y: auto; 
                padding: 20px; 
                max-width: 80vw;
            }

            #id_text{
                width: 97vw;
                border: none;
            }

        </style>
    </head>
    <body>
        {{user.id|json_script:"user_id_json"}}
        {{page.id|json_script:"page_id_json"}}
        <script>
            let user_id = JSON.parse(document.getElementById('user_id_json').textContent);
            let page_id = JSON.parse(document.getElementById('page_id_json').textContent);

            var url = "";
            const origin = window.location.origin;

            const data = {
                "user_id": user_id,
                "page_id": page_id
            }

            const requestOptions = {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json' 
                },
                body: JSON.stringify(data) 
            };

            function bookmark(){
                url = origin + "/bookmark/add"
                fetch(url, requestOptions)
                .then(response => {
                    if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                    }
                    return response.json(); 
                })
                .then(data => {
                    console.log('Response data:', data);
                    document.location.reload();
                })
                .catch(error => {
                    console.error('Error:', error);
                    
                });

            }

            function unbookmark(){
                url = origin + "/bookmark/delete"

                fetch(url, requestOptions)
                .then(response => {
                    if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                    }
                    return response.json(); 
                })
                .then(data => {
                    console.log('Response data:', data);
                    document.location.reload();
                })
                .catch(error => {
                    console.error('Error:', error);
                    
                });
            }

        </script>
        <a href="/"><button>Go to home</button></a>
        {% if user.is_anonymous %}
            <a href="/accounts/login" style="float: right;"><button>Login</button></a>
        {% else %}
            <a href="/accounts/logout" style="float: right;"><button>Logout</button></a>
        {%endif%}
        {% if not bookmarked %}
            <button onclick=bookmark() id="bookmark">Bookmark!</button>
        {% else %}
            <button onclick=unbookmark()>Unbookmark</button>
        {% endif %}
        <h1>{{page.title}} </h1>

        <div class="editable-div"><div contenteditable="true" class="editable-content"> {{page.data | safe | linebreaks}} </div></div>

        {% if tags|length > 0 %}
        <h3>Tags:</h3>
        <ul>
        {% for tag in tags %}
            <li> <a href="/tag/{{tag.id}}/{{tag.name}}">{{tag.name}}</a> </li>
        {% endfor %}
        </ul>
        {% endif %}

        {% if user.is_authenticated %}
        <h3>add comment:</h3>
        <form action="/comments/add?user_id={{user.id}}&page_id={{page.id}}" method="POST">
            {% csrf_token %}
            <p>
                <div style="border: solid 2px red;"> 
                <div class-"limited-height-div" style="width:100vw;">{{comment_form.text}}</div>
                {{comment_form.user_id.as_hidden}}
                {{comment_form.page_id.as_hidden}}
                </div>
                </div>
            </p>
            <input type="submit" value="Submit">
        </form>
        {% else %}
            <p>Please login to comment</p>
        {% endif %}


        {% if comments|length > 0%}
            <h3> comments: </h3>
            <ul>
            {% for comment in comments %}
                <div style="border: 2px solid black;">
                    <p><a href="/user/{{comment.user.id}}">{{comment.user.username}}</a> commented on {{comment.date_created}}: </p>
                    <p>{{comment.text}}</p>
                </div>
            {% endfor %}
            </ul>
        {% endif %}
    </body>
</html>

python/web/learn_site/info/templates/edit_tag.html
<html>
    <body>
        <h1>edit tag : {{tag.name}}</h1>

        <form action="" method="POST">
            {% csrf_token %}
            <ul>{{form_tag.as_ul}}</ul>
            <input type="submit" value="submit">
        </form>
    </body>
</html>

python/web/learn_site/info/templates/index.html
<head>
</head>
<body>
    <h1>Hi!<h1>

    <a href="/page/add"><button>add page</button></a>
    <h3>Pages:</h3>
    <ul>   
    {% for page in pages %}
        <li><a href="/page/{{page.id}}/{{page.title}}">{{page.title}}</a></li>    
    {% endfor %}
    </ul>
    <ul>
    <h3>Tags: </h3>
    {% for tag in tags %}
        <li><a href="/tag/{{tag.id}}/{{tag.name}}">{{tag.name}}</a></li>
    {% endfor %}
    </ul>
</body>

python/web/learn_site/info/templates/tag_glossary.html
<html>
    <body>
        <h1>tag glossary</h1>
        <ul>
            {% for tag in tags %}
            <li><a href="/tag/{{tag.id}}/{{tag.name}}">{{tag.name}}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>

python/web/learn_site/info/templates/tag_page.html
<html>
    <head>
    </head>
    <body>
        <style>
            #logout {
                float: right
            }
            
            #login {
                float: right
            }

        </style>

        <a href="/"><button>Home</button></a>
        <a href="/tags/glossary"><button>All tags</button></a>
        {% if user.is_authenticated %}
        <a href="/tags/edit/{{tag.id}}/{{tag.name}}"><button>edit tag</button></a> 
        <a id="logout" href="/accounts/logout"><button>logout</button></a>
        {% endif %}
        {% if user.is_anonymous %}
        <a id="login" href="/accounts/login"><button>login</button></a>
        {% endif %}
        
        <h1>{{tag.name}}</h1>

        <p>{{tag.details}}</p>
        {% if pages|length > 0 %}
        <h3>Pages:</h3>
        <ul>
            {% for page in pages %}
            <li><a href="/page/{{page.id}}/{{page.title}}">{{page.title}}</a></li>
            {% endfor %}
        </ul>
        {% endif %}
    </body>
</html>